version: "3.9"

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - iiimef_project/.env.db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - iiimef_project/.env
    ports:
      - "8000:8000"
    depends_on:
      - db