-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 23:01:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema redonkulator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema redonkulator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `redonkulator` DEFAULT CHARACTER SET utf8;
USE `redonkulator`;

-- -----------------------------------------------------
-- Table `redonkulator`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`exercises`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`exercises`
(
    `exercise`   VARCHAR(45) NOT NULL,
    `evolution`  VARCHAR(8)  NOT NULL COMMENT 'Sequence, typically in the form of month-year or just year, depending on the frequency.',
    `start_date` DATETIME    NULL,
    `end_date`   DATETIME    NULL,
    PRIMARY KEY (`exercise`, `evolution`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redonkulator`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`units`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`units`
(
    `uic`        VARCHAR(45) NOT NULL,
    `short_name` VARCHAR(45) NOT NULL,
    `long_name`  VARCHAR(45) NOT NULL,
    `mcc`        VARCHAR(45) NULL,
    `ruc`        VARCHAR(45) NULL,
    PRIMARY KEY (`uic`),
    UNIQUE INDEX `short_name_UNIQUE` (`short_name` ASC) VISIBLE,
    UNIQUE INDEX `long_name_UNIQUE` (`long_name` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redonkulator`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`users`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`users`
(
    `edipi`      INT         NOT NULL,
    `rank_abbr`  VARCHAR(45) NULL,
    `last_name`  VARCHAR(45) NULL,
    `first_name` VARCHAR(45) NULL,
    `email`      VARCHAR(45) NULL,
    `phone`      VARCHAR(45) NULL,
    PRIMARY KEY (`edipi`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redonkulator`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`permissions`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`permissions`
(
    `id`                 INT         NOT NULL AUTO_INCREMENT,
    `parent_user_edipi`  INT         NOT NULL,
    `user_edipi`         INT         NOT NULL,
    `exercise_evolution` VARCHAR(45) NOT NULL,
    `unit_uic`           VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_parent_user_edipi_idx` (`parent_user_edipi` ASC) VISIBLE,
    INDEX `fk_user_edipi_idx` (`user_edipi` ASC) VISIBLE,
    INDEX `fk_exercise_evolution_idx` (`exercise_evolution` ASC) VISIBLE,
    INDEX `fk_permissions_units_idx` (`unit_uic` ASC) VISIBLE,
    CONSTRAINT `fk_parent_user_edipi`
        FOREIGN KEY (`parent_user_edipi`)
            REFERENCES `redonkulator`.`users` (`edipi`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_edipi`
        FOREIGN KEY (`user_edipi`)
            REFERENCES `redonkulator`.`users` (`edipi`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_exercise_evolution`
        FOREIGN KEY (`exercise_evolution`)
            REFERENCES `redonkulator`.`exercises` (`exercise`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_permissions_units`
        FOREIGN KEY (`unit_uic`)
            REFERENCES `redonkulator`.`units` (`uic`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redonkulator`.`after_actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`after_actions`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`after_actions`
(
    `id`                  INT         NOT NULL AUTO_INCREMENT,
    `exercises_exercise`  VARCHAR(45) NOT NULL,
    `exercises_evolution` VARCHAR(8)  NOT NULL,
    `data`                BLOB        NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_after_actions_exercises_idx` (`exercises_exercise` ASC, `exercises_evolution` ASC) VISIBLE,
    CONSTRAINT `fk_after_actions_exercises`
        FOREIGN KEY (`exercises_exercise`, `exercises_evolution`)
            REFERENCES `redonkulator`.`exercises` (`exercise`, `evolution`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redonkulator`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`equipment`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`equipment`
(
    `tamcn`                  INT           NOT NULL,
    `nomen`                  VARCHAR(45)   NULL,
    `type`                   VARCHAR(45)   NULL,
    `length`                 DECIMAL(7, 2) NULL,
    `width`                  DECIMAL(7, 2) NULL,
    `height`                 DECIMAL(7, 2) NULL,
    `sqft`                   DECIMAL(7, 2) NULL,
    `cuft`                   DECIMAL(7, 2) NULL,
    `gvw_combat_loaded`      DECIMAL(7, 2) NULL,
    `fuel_capacity`          DECIMAL(7, 2) NULL,
    `burn_rate`              DECIMAL(7, 2) NULL COMMENT 'MPG or MPH',
    `crew`                   INT           NULL,
    `passengers`             INT           NULL,
    `fuel_payload`           DECIMAL(7, 2) NULL,
    `water_payload`          DECIMAL(7, 2) NULL,
    `payload`                DECIMAL(7, 2) NULL,
    `pallets_palcons`        INT           NULL,
    `sixcon_transpo`         INT           NULL,
    `quadcon`                INT           NULL,
    `isocon`                 INT           NULL,
    `combat_load_pallet`     INT           NULL,
    `combat_load_pallet_wt`  DECIMAL(7, 2) NULL,
    `aslt_rate_pallet`       DECIMAL(7, 2) NULL,
    `aslt_rate_pallet_wt`    DECIMAL(7, 2) NULL,
    `sustain_rate_pallet`    DECIMAL(7, 2) NULL,
    `sustain_rate_pallet_wt` DECIMAL(7, 2) NULL,
    PRIMARY KEY (`tamcn`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redonkulator`.`equip_on_hand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`equip_on_hand`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`equip_on_hand`
(
    `id`      INT         NOT NULL AUTO_INCREMENT,
    `uic`     VARCHAR(45) NULL,
    `tamcn`   INT         NULL,
    `on_hand` INT         NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_equip_on_hand_units_idx` (`uic` ASC) VISIBLE,
    INDEX `fk_equip_on_hand_equipment_idx` (`tamcn` ASC) VISIBLE,
    CONSTRAINT `fk_equip_on_hand_units`
        FOREIGN KEY (`uic`)
            REFERENCES `redonkulator`.`units` (`uic`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_equip_on_hand_equipment`
        FOREIGN KEY (`tamcn`)
            REFERENCES `redonkulator`.`equipment` (`tamcn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redonkulator`.`equip_utilization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redonkulator`.`equip_utilization`;

CREATE TABLE IF NOT EXISTS `redonkulator`.`equip_utilization`
(
    `id`                  INT         NOT NULL AUTO_INCREMENT,
    `uic`                 VARCHAR(45) NOT NULL,
    `exercises_exercise`  VARCHAR(45) NOT NULL,
    `exercises_evolution` VARCHAR(8)  NOT NULL,
    `qty`                 INT         NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_equip_utilization_units1_idx` (`uic` ASC) VISIBLE,
    INDEX `fk_equip_utilization_exercises1_idx` (`exercises_exercise` ASC, `exercises_evolution` ASC) VISIBLE,
    CONSTRAINT `fk_equip_utilization_units1`
        FOREIGN KEY (`uic`)
            REFERENCES `redonkulator`.`units` (`uic`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_equip_utilization_exercises1`
        FOREIGN KEY (`exercises_exercise`, `exercises_evolution`)
            REFERENCES `redonkulator`.`exercises` (`exercise`, `evolution`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
