# Generated by Django 3.2 on 2021-05-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('evolution', models.CharField(max_length=8, unique=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('logo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('uic', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=45, unique=True)),
                ('long_name', models.CharField(max_length=100, unique=True)),
                ('mcc', models.CharField(max_length=45, unique=True)),
                ('ruc', models.CharField(max_length=45, unique=True)),
                ('type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=45, unique=True)),
                ('edipi', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
            ],
        ),
    ]
